# .github/workflows/release.yml
# Start Homebrew Releaser when a new tag is created
on:
  push:
    branches:
      - "main"

jobs:
  homebrew-releaser:
    runs-on: ubuntu-latest
    name: homebrew-releaser
    steps:
      - uses: actions/checkout@v4

      - name: Configure 1Password Service Account
        uses: 1password/load-secrets-action/configure@v1
        with:
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Load GitHub credentials
        id: load-github-credentials
        uses: 1password/load-secrets-action@v1
        with:
          export-env: false
        env:
          HOMEBREW_TAP_GITHUB_TOKEN: op://CICD/github-easytocloud-brew/credential 

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GH_TOKEN: ${{ steps.load-github-credentials.outputs.HOMEBREW_TAP_GITHUB_TOKEN  }}

      - name: Release aws-profile-organizer to easytocloud/homebrew-tap
        uses: Justintime50/homebrew-releaser@v1
        with:
          homebrew_owner: easytocloud
          homebrew_tap: homebrew-tap
          formula_folder: Formula
          github_token: ${{ steps.load-github-credentials.outputs.HOMEBREW_TAP_GITHUB_TOKEN }}
          commit_owner: homebrew-releaser
          commit_email: homebrew-releaser@easytocloud.com
          depends_on: |
            "easytocloud/tap/zsh_functions" 
          install: |
            bin.install "distribution/bin/aws-profile-organizer-setup"
            bin.install "distribution/bin/aws-profile-organizer-rc"
            bin.install "distribution/bin/aws-profile-organizer-set-defaults"

            zsh_function.install Dir["distribution/functions/*"]
            bash_completion.install "completions/aws-profile-organizer-completion.bash"
            zsh_completion.install "completions/aws-profile-organizer-completion.zsh"
            
            # Create a wrapper script to source the functions and completions
            (bin/"aws-profile-organizer").write <<~EOS
              #!/bin/bash
              if [ -n "$BASH_VERSION" ]; then
                echo "Seting up aws-profile-organizer for Bash"
                source "#{zsh_function}/awsenv"
                source "#{zsh_function}/awsprofile"
                source "#{bash_completion}/aws-profile-organizer-completion.bash"
              elif [ -n "$ZSH_VERSION" ]; then
                echo "Seting up aws-profile-organizer for Zsh"
                source "#{zsh_function}/awsenv"
                source "#{zsh_function}/awsprofile"
                source "#{zsh_completion}/aws-profile-organizer-completion.zsh"
                autoload -U compinit && compinit
              else
                echo "Unsupported shell. Please use Bash or Zsh."
              fi
            EOS
            
            chmod 0755, bin/"aws-profile-organizer"

          caveats: |
            To use aws-profile-organizer, add the following to your .bashrc or .zshrc:
              source "$(brew --prefix)/bin/aws-profile-organizer"

          test: |
            assert_match "Usage: awsenv", shell_output("bash -c 'source #{bin}/aws-profile-organizer && awsenv --help'")
            assert_match "Usage: awsprofile", shell_output("bash -c 'source #{bin}/aws-profile-organizer && awsprofile --help'")
          update_readme_table: true
          skip_commit: false
          debug: true
